language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
